-- MySQL Script generated by MySQL Workbench
-- Mon Mar 15 22:31:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema commutator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `commutator` ;

-- -----------------------------------------------------
-- Schema commutator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `commutator` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `commutator` ;

-- -----------------------------------------------------
-- Table `commutator`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(300) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `role` VARCHAR(300) NOT NULL,
  `status` VARCHAR(300) NOT NULL,
  `first_name` VARCHAR(500) NULL,
  `last_name` VARCHAR(500) NULL,
  `photo` LONGBLOB NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_email_uindex` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `commutator`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `UID` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UID_UNIQUE` (`UID` ASC) VISIBLE,
  INDEX `fk_device_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_device_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `commutator`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`setting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `value` VARCHAR(1000) NOT NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_setting_device1_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_setting_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `commutator`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`channel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(300) CHARACTER SET 'utf8' NOT NULL COMMENT 'Тип каналу (Диммер, Реле)',
  `value` INT NOT NULL COMMENT 'Значення каналу (ШІМ 0-255 ардуїнівських)',
  `working_time` INT NULL COMMENT 'Час роботи до при спрацюванні',
  `recheck_time` INT NULL COMMENT 'Час роботи до наступного оновлення даних',
  `pid_kp` DOUBLE NOT NULL COMMENT 'PID коефіцієнт kp',
  `pid_ki` DOUBLE NOT NULL COMMENT 'PID коефіцієнт ki',
  `pid_kd` DOUBLE NOT NULL COMMENT 'PID коефіцієнт kd',
  `pid_mode` VARCHAR(300) NOT NULL COMMENT 'PID режим роботи (за наростанням або за спаданням)',
  `control_mode` VARCHAR(300) NOT NULL COMMENT 'Режим роботи каналу (РУЧНИЙ, PID-автомат, ПЛАНІВНИК, ТАЙМЕР)',
  `name_web` VARCHAR(300) NOT NULL COMMENT 'Назва для відображення на веб-сторінці',
  `name_in_device` VARCHAR(20) NOT NULL COMMENT 'Назва для відображення на контролері',
  `description` VARCHAR(3000) NULL COMMENT 'Опис (необов\'язково) для відображення на веб сторінці',
  `device_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_channel_device1_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_channel_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `commutator`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`sensor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `min_value` DOUBLE NOT NULL,
  `max_value` DOUBLE NOT NULL,
  `step` DOUBLE NOT NULL,
  `type` VARCHAR(300) NULL,
  `channel_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sensor_channel1_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `commutator`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`schedule` (
  `id` INT NOT NULL,
  `name` VARCHAR(300) NOT NULL,
  `start_time` TIMESTAMP NOT NULL,
  `value` INT NOT NULL,
  `channel_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_schedule_channel1_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `commutator`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`timer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`timer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `day` VARCHAR(300) NOT NULL,
  `start_at` TIME NOT NULL,
  `value_start` INT NOT NULL,
  `end_at` TIME NOT NULL,
  `value_end` INT NOT NULL,
  `channel_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_timer_channel1_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_timer_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `commutator`.`channel` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commutator`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commutator`.`data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `time` TIMESTAMP NOT NULL,
  `value` DOUBLE NOT NULL,
  `unit` VARCHAR(300) NOT NULL,
  `sensor_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_data_sensor1_idx` (`sensor_id` ASC) VISIBLE,
  INDEX `fk_data_device1_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `fk_data_sensor1`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `commutator`.`sensor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_data_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `commutator`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
